spring.application.name=Cinema_Booking
# 1. Cấu hình kết nối Cơ sở dữ liệu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cinema_booking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Thay "123456" bằng mật khẩu tài khoản MySQL thực tế ở máy của em
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Cấu hình Hibernate tự động sinh bảng (CHÍ MẠNG)
# Lệnh 'update' giúp tự động tạo bảng mới nếu chưa có, hoặc cập nhật thêm cột nếu em sửa đổi Entity sau này
spring.jpa.hibernate.ddl-auto=update

# 3. Hiển thị các câu lệnh SQL dưới bảng Console để em tiện theo dõi và debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Đã bật lại Spring Security (cần thiết cho OAuth2 hoạt động)
# 5. Cấu hình OAuth2 Google & Facebook

spring.security.oauth2.client.registration.facebook.scope=public_profile,email

# Ép Google chạy qua chuẩn OAuth2 thường (bỏ qua OpenID) để kích hoạt CustomOAuth2UserService
spring.security.oauth2.client.registration.google.scope=profile,email
