spring.application.name=Cinema_Booking
# 1. Cấu hình kết nối Cơ sở dữ liệu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cinema_booking_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Thay "123456" bằng mật khẩu tài khoản MySQL thực tế ở máy của em
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Cấu hình Hibernate tự động sinh bảng (CHÍ MẠNG)
# Lệnh 'update' giúp tự động tạo bảng mới nếu chưa có, hoặc cập nhật thêm cột nếu em sửa đổi Entity sau này
spring.jpa.hibernate.ddl-auto=update

# 3. Hiển thị các câu lệnh SQL dưới bảng Console để em tiện theo dõi và debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. Tạm thời tắt Security để kiểm tra tạo bảng (khi nào code xong luồng đăng nhập thì bật lại)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration